---
- name: Make sure docker container storage exists
  ansible.builtin.file:
    path: "{{ docker_storage_mount_point }}"
    state: directory
    mode: '0755'

# - name: Update resolv.conf with Google DNS (fix issues with registries)
#   ansible.builtin.command:
#     cmd: "echo 'nameserver 8.8.8.8' | sudo tee /etc/resolv.conf > /dev/null"
#     become: true
