---

- name: Create a directory for all services
  ansible.builtin.file:
    path: "{{ machine_data_path }}/docker/{{ item.name }}"
    state: directory
    mode: '0755'
  loop: "{{ deploy_containers_services }}"

- name: Copy service templates to corresponding folders
  ansible.builtin.template:
    src: "{{ item.name }}/docker-compose.yml.j2"
    dest: "{{ machine_data_path }}/docker/{{ item.name }}/docker-compose.yml"
    mode: '0644'
  loop: "{{ deploy_containers_services }}"

- name: Copy envs of the containers that have them
  ansible.builtin.template:
    src: "{{ item.name }}/.env.j2"
    dest: "{{ machine_data_path }}/docker/{{ item.name }}/.env"
    mode: '0644'
  loop: "{{ deploy_containers_services }}"
  when: item.has_env

- name: Deploy services to Docker
  ansible.builtin.command:
    cmd: "docker compose -f {{ machine_data_path }}/docker/{{ item.name }}/docker-compose.yml up -d"
  changed_when: false
  loop: "{{ deploy_containers_services }}"
