---
setup_backups_storage_script_location: "{{ machine_data_path }}/storage-backup"
setup_backups_config_location: "{{ machine_data_path }}/rclone"
setup_backups_cloudmnt_location: /cloudmnt
setup_backups_git_location: "{{ storage_mount_point }}/git-backups"

repositories_to_backup:
  - name: spenser
  - name: one-and-done
  - name: personal-portfolio
  - name: homelab-ansible
  - name: homelab-dashboards
  - name: adji-boto-solver-alfabeta
  - name: adji-boto-solver
  - name: expense-data-sorter
  - name: bagsplus-landing-page
  - name: personal-file-system
  - name: fb-group-scraper
  - name: ansible-homelab
  - name: BAGSPLUS-Extra-Utils
  - name: RaulRohjans
  - name: github-readme-stats
  - name: bgs-webadmin
  - name: travelling-salesman-problem-java
  - name: travelling-salesman-problem
  - name: fuel2you
  - name: bgs_admin
  - name: GestaoRHPOO
  - name: tvtime-backup-tool
  - name: webchat-pw
  - name: zippyshare-direct-url
  - name: Meo-Wifi-logger
  - name: contas-bancarias-aefp
  - name: gestao-software-ipw
  - name: site-pessoal-ipw
  - name: youtube-playlist-sync
  - name: AnimeWatcher-WEB
  - name: Anime-Update-Scraper
  - name: AnimeWatcher-Android
  - name: animewatch-cli
  - name: prestashopbeam
  - name: ConsultasCentrality
  - name: TypingRacerV2
  - name: TypingRacerV1
  - name: GasCalc
  - name: AvaliacaoExtraordinaria
  - name: Tutorias
  - name: eco-challenger

