---
- name: Install rclone
  ansible.builtin.apt:
    name: rclone
    state: present
  become: true

- name: Create rclone config directory
  ansible.builtin.file:
    path: "{{ setup_backups_config_location }}"
    state: directory
    mode: '0755'

- name: Copy rclone configuration
  ansible.builtin.template:
    src: rclone.conf.j2
    dest: "{{ setup_backups_config_location }}/rclone.conf"
    mode: '0755'
  become: true
